# Generated by Django 4.1.3 on 2023-01-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='successful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.FloatField()),
                ('profits', models.BooleanField()),
            ],
        ),
    ]
