# Generated by Django 4.1.3 on 2023-01-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_picture_movies_premiered'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de estreno'),
        ),
    ]
