# Generated by Django 4.1.3 on 2023-01-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_studio_creation_studio_image_studio_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='director_image'),
        ),
        migrations.AddField(
            model_name='director',
            name='retired',
            field=models.BooleanField(default=False, verbose_name='Retirado'),
        ),
    ]
