# Generated by Django 4.1.3 on 2023-01-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_windows_alter_movies_picture_alter_movies_premiered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='text',
            field=models.CharField(max_length=10000, verbose_name='Contenido'),
        ),
    ]
