# Generated by Django 4.1.3 on 2023-01-31 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_windows_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windows',
            options={'verbose_name': 'Window', 'verbose_name_plural': 'Windows'},
        ),
    ]
